config/routes.rb
Rails.application.routes.draw do
  delete 'cocktails/:id', to: 'cocktails#destroy', as: :destroy
  resources :cocktails, only: [:index, :new, :create, :show] do
    resources :doses, only: [:new, :create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  mount_uploader :photo, PhotoUploader

  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, uniqueness: true
  validates :name, presence: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }

end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, uniqueness: true
  validates :name, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [:show]
  def index
    @cocktails = Cocktail.all
  end

  def show(); end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    @cocktail.save
  end

  def destroy
    @cocktails = Cocktail.find(params[:id])
    @cocktails.destroy
    redirect_to :cocktails
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_params
    params.require(:cocktail).permit(:name, :body, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(cocktail_params)
    @dose.cocktail = @cocktail
    @dose.save
    redirect_to :cocktails
  end

  def destroy
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@cocktail)
  end

  private

  def cocktail_params
    params.require(:dose).permit(:description, :cocktail_id, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cocktails/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= simple_form_for cocktail do |f| %>
        <%= f.input :name %>
        <%= f.submit class: 'btn btn-primary' %>
        <%= f.input :photo %>
        <%= f.input :photo_cache, as: :hidden %>
      <% end %>
    </div>
  </div>
</div>

app/views/cocktails/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= image_path('banner.jpg') %>');">
  <div class="container">
    <h1>Bienvenue chez CocktailLand !</h1>
    <p>Avec les cocktails, la fête est bien folle</p>
    <a class="btn btn-flat" href="#"><%= link_to "Créer un cocktail", new_cocktail_path %></a>
  </div>
</div>


<div class="container">
  <% @cocktails.each do |cocktail| %>
    <% if cocktail.photo.present? %>
      <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= cl_image_path(cocktail.photo, width: 400, height: 300, crop: :fill)%>);">
         <h4> <%= link_to cocktail.name, cocktail_path(cocktail.id) %> </h4>
      </div>
    <% end %>
  <% end %>
</div>

<!-- app/views/articles/index.html.erb -->

app/views/cocktails/new.html.erb
<p>Create new cocktail : </p>

<%= render 'form', cocktail: @cocktail %>

<p> <%= link_to "Retour au menu", cocktails_path %> </p>

app/views/cocktails/show.html.erb
<div class="wrap">
  <div class="box">
    <p> Voici les ingrédients pour faire ton <%= @cocktail['name'] %> :</p>

      <ul <% @cocktail.doses.each do |dose| %>>
        <li class="border-show">   <%= dose.description %> :
          <%= dose.ingredient.name %>
          <%= link_to "Delete", cocktail_dose_path(@cocktail, dose),
          method: :delete %></li>
            <% end %>
      </ul>
      <div class="align-button">
        <div class="btn btn-success btn-add-dose"> <%= link_to "Ajouter une dose", new_cocktail_dose_path(@cocktail) %>
        </div>
        <div class="btn btn-danger btn-delete"> <%= link_to "Effacer la recette", destroy_path(@cocktail.id), method: :delete, data: { confirm: "Are you sure?" } %>
        </div>
      </div>
      <p class="btn-menu"> <%= link_to "Retour au menu", cocktails_path %> </p>
  </div>
  <div class="box">
    <%= cl_image_tag @cocktail.photo, height: 300, width: 400, crop: :fill %>
  </div>
</div>

app/views/doses/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= simple_form_for [cocktail, dose] do |f| %>
        <%= f.input :description %>
        <%= f.association :ingredient %>
        <%= f.submit class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/doses/new.html.erb
<p>Create new cocktail : </p>

<%= render 'form', dose: @dose, cocktail: @cocktail %>

<p> <%= link_to "Créer un nouveau cocktail", new_cocktail_path %> </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  </head>

  <body>
    <%= yield %>
    <%= javascript_include_tag "application" %>
    <%= javascript_pack_tag "application" %>
</body>
  </body>
</html>